### ISSUE TITLE
[Project Tracking] Baseline Repository Setup

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/weaver#14]
This is a meta-bug for tracking features for this repository.  This list may already have things completed, I'm merely opening all known tasks for thorough/completeness.

- [x] Set up `CONTRIBUTING.md` outlining how to start contributing.
- [x] Set up github actions and requirements
  - [ ] Formalize requirements for two approvers on every PR, each from different companies.
  - [x] Ensure horizontal actions are enabled, e.g. CLA checker.
- [x] Add enforcement of dependency choices w/ CNCF guidelines (looked to otel-rust to see what they do, this may be ad-hoc right now)
- [x] Look into better `CHANGELOG.md` devex (e.g. chgloggen from collector)
- [ ] Add stale PR bot
