### ISSUE TITLE
Migrate all codegen to weaver

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/weaver#227]
- [x] Document how to do codgen (see https://github.com/open-telemetry/weaver/blob/main/crates/weaver_forge/README.md)
- [X] We want a mechanism to not force folks to write JQ (see #246, release v0.7.0)
- [ ] Migrate Languages (from https://opentelemetry.io/docs/languages/)
  - [x] Migrate [C++](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/buildscripts/semantic-convention/)  - https://github.com/open-telemetry/opentelemetry-cpp/pull/3105
  - [x] Migrate .NET (@joaopgrassi) - https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1944
  - [x] Migrate Erlang/Elixir (@bryannaegele) - https://github.com/open-telemetry/opentelemetry-erlang/pull/733
  - [x] Migrate Go (@trisch-me) - Go maintainers want to do it themselves
    - Prototype: https://github.com/open-telemetry/opentelemetry-go/pull/5793
    - Final(?) PR: https://github.com/open-telemetry/opentelemetry-go/pull/5898
  - [x] Migrate Python (@lmolkova) - https://github.com/open-telemetry/opentelemetry-python/pull/4091
  - [x] Migrate Java (@jsuereth) - https://github.com/open-telemetry/semantic-conventions-java/pull/70
  - [x] Migrate JavaScript / Typescript (@MSNev) - https://github.com/open-telemetry/opentelemetry-js/pull/4690
  - [ ] Migrate Ruby - https://github.com/open-telemetry/opentelemetry-ruby/pull/1651
     - [Source](https://github.com/open-telemetry/opentelemetry-ruby/blob/main/semantic_conventions/)
     - Contributor @ahayworth 
  - [x] Migrate Rust (@lquerel) - https://github.com/open-telemetry/opentelemetry-rust/pull/2098
  - [x] Migrate PHP (@brettmc ?) - https://github.com/open-telemetry/opentelemetry-php/issues/1396
  - [ ] Migrate Swift - https://github.com/open-telemetry/opentelemetry-swift/issues/598
    - [Source](https://github.com/open-telemetry/opentelemetry-swift/tree/main/Scripts/semantic-convention)
    - Contributor @Sherlouk
  - [x] Scour for other SIG usage (@jsuereth)
- [ ] Collector metadatagen (@jsuereth)
     - Prototype in the works https://github.com/open-telemetry/opentelemetry-collector/pull/11064

**Comment by joaopgrassi** [comment]
For reference, .NET semconv "package" is here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.SemanticConventions

**Comment by trisch-me** [comment]
for the golang - https://github.com/open-telemetry/opentelemetry-go-build-tools/tree/main/semconvgen

**Comment by trentm** [comment]
For Node.js/JS/TS https://github.com/open-telemetry/opentelemetry-js/pull/4690 will be migrating semconv codegen to use weaver.

**Comment by brettmc** [comment]
PHP migration completed and can be checked off...

**Comment by marcalff** [comment]
@open-telemetry/weaver-maintainers 

Please take a look at the opentelemetry-cpp migration to weaver:

* https://github.com/open-telemetry/opentelemetry-cpp/pull/3105

Looking for any feedback or suggestions on the weaver / jinja code in particular.

**Comment by lquerel** [comment]
@marcalff 

> Looking for any feedback or suggestions on the weaver / jinja code in particular.

Very nice use of Weaver. 

On your side, do you see any areas for improvement in Weaver that would make things easier for you?

**Comment by marcalff** [comment]
> @marcalff
> 
> > Looking for any feedback or suggestions on the weaver / jinja code in particular.
> 
> Very nice use of Weaver.
> 
> On your side, do you see any areas for improvement in Weaver that would make things easier for you?

Yes, I have a few suggestions.

When a developer find a weaver.yaml file, of a jinja file, and sees it the first time,
it gets extremely challenging to know what to do about it, if a change even minor is required in the file.

If I find a C++ or java file, I know where to find doc about the C++ or java library, language syntax, etc.

If I find weaver.yaml, I can only stare at the content and be stuck.

Do not assume people will know of, or even have heard of, weaver and jinja, and even less that they will know where to find doc about it.

This is why I added systematically pointers to the DOC, in comments, in these files, for opentelemetry-cpp.

I think it will be beneficial to add that in the examples and templates.

By pointers to the doc, I mean something like this:

```
{#
  Copyright The OpenTelemetry Authors
  SPDX-License-Identifier: Apache-2.0
  This file is:
  - a Jinja template,
  - used to generate semantic conventions,
  - using weaver.
  For doc on the template syntax:
  https://jinja.palletsprojects.com/en/3.0.x/
  For doc on the semantic conventions:
  https://github.com/open-telemetry/semantic-conventions
  For doc on weaver:
  https://github.com/open-telemetry/weaver
#}```

**Comment by marcalff** [comment]
Also, systematically adding a comment in the generated code, to indicate:

* that is is generated code
* where it is generated from

should be strongly suggested as a best practice, in the jinja templates.

Not all SIG are doing this, from what I could find.

**Comment by lquerel** [comment]
Created these 2 GH issues:
- https://github.com/open-telemetry/weaver/issues/439
- https://github.com/open-telemetry/weaver/issues/440
